project13/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *

import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('muni/',muni,name='muni'),
    path('gaanu/',gaanu,name='gaanu'),
    path('specific/',include('specific.urls')),
    
]

specific/urls.py
from specific.views import *
from django.urls import path

app_name='specific'

urlpatterns=[
    path('bhanu/',bhanu,name='bhanu'),
    path('kavitha/',kavitha,name='kavitha'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.


def muni(request):
    return render(request,'muni.html')

def gaanu(request):
    return render(request,'gaanu.html')

specific/views.py
from django.shortcuts import render

# Create your views here.

def bhanu(request):
    return render(request,'bhanu.html')

def kavitha(request):
    return render(request,'kavitha.html')

templates/bhanu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> This is a bhanu html file</h1>
    </center>
</body>
</html>

templates/gaanu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>It is a beautifull name</h1>
    </center>
</body>
</html>

templates/kavitha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is kavitha html</h1>
    </center>
        
</body>
</html>

templates/muni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is a muni html page</h1>
        <a href="{% url 'gaanu' %}">gaana</a>
        <a href="{% url 'specific:kavitha' %}">kavitha</a>
        <a href="{% url 'specific:bhanu' %}">bhanu</a>
    </center>
</body>
</html>